# Copyright (c) 1993-1995 by Argonaut Technologies Limited. All rights reserved.
#
# $Id: makefile 1.3 1995/07/28 19:03:37 sam Exp $
# $Locker:  $
#
# Makefile for Brender C library hooks built with Watcom C32
#
.IMPORT: BASE_DIR MAKE_EXT
TARGET_TYPE:=LIB

LIB_PART:=brst

INCLUDES:=-I$(BASE_DIR)\inc -I$(BASE_DIR)\fw 

OBJS_C=\
	$(BLD_DIR)/stdfile$(OBJ_EXT)\
	$(BLD_DIR)/stdmem$(OBJ_EXT)\
	$(BLD_DIR)/stddiag$(OBJ_EXT)\

.INCLUDE: $(BASE_DIR)/makedefs$(MAKE_EXT)

